### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by JHite** [traweezy/traweezy#1]
You spelled development wrong but everything else looks great otherwise!

> Wanting to branch out into other areas of **developpment**

**Comment by traweezy** [comment]
lol Fuck

**Comment by traweezy** [comment]
Fixed with the the most recent commit "Wanting to branch out into other areas of development using languages like Rust"

thanks, Jimi

P.S.

Learn Rust, lets build something babey, I mastered Front end, I can build a beautiful UI, let fuck some shit up on the back end.

**Comment by traweezy** [comment]
Closing Issue
